// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210429150036_FirstCreate")]
    partial class FirstCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gestion_RH.Models.Bassin", b =>
                {
                    b.Property<Guid>("BassinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("NomBassin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BassinId");

                    b.ToTable("Bassins");
                });

            modelBuilder.Entity("Gestion_RH.Models.Observateur", b =>
                {
                    b.Property<Guid>("ObservateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("NomPrenomObservateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ObservateurId");

                    b.HasIndex("StationId");

                    b.ToTable("Observateurs");
                });

            modelBuilder.Entity("Gestion_RH.Models.RelativeHumidity", b =>
                {
                    b.Property<Guid>("RelativeHumidityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateObservation")
                        .HasColumnType("datetime2");

                    b.Property<int>("Heur")
                        .HasColumnType("int");

                    b.Property<float>("Hum")
                        .HasColumnType("real");

                    b.Property<float>("Mou")
                        .HasColumnType("real");

                    b.Property<Guid?>("ObservateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Sec")
                        .HasColumnType("real");

                    b.Property<Guid?>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ThermometreMA")
                        .HasColumnType("real");

                    b.Property<float>("ThermometreMI")
                        .HasColumnType("real");

                    b.Property<float>("ThermometreMax")
                        .HasColumnType("real");

                    b.Property<float>("ThermometreMin")
                        .HasColumnType("real");

                    b.Property<float>("ThermometreMoyMaxMin")
                        .HasColumnType("real");

                    b.HasKey("RelativeHumidityId");

                    b.HasIndex("ObservateurId");

                    b.HasIndex("StationId");

                    b.ToTable("RelativeHumiditys");
                });

            modelBuilder.Entity("Gestion_RH.Models.Station", b =>
                {
                    b.Property<Guid>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("BassinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomStation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationId");

                    b.HasIndex("BassinId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Gestion_RH.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gestion_RH.Models.Observateur", b =>
                {
                    b.HasOne("Gestion_RH.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Gestion_RH.Models.RelativeHumidity", b =>
                {
                    b.HasOne("Gestion_RH.Models.Observateur", "Observateur")
                        .WithMany()
                        .HasForeignKey("ObservateurId");

                    b.HasOne("Gestion_RH.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId");

                    b.Navigation("Observateur");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Gestion_RH.Models.Station", b =>
                {
                    b.HasOne("Gestion_RH.Models.Bassin", "Bassin")
                        .WithMany()
                        .HasForeignKey("BassinId");

                    b.Navigation("Bassin");
                });
#pragma warning restore 612, 618
        }
    }
}
